train_subs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
val_subs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
slicing processed dataset
/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/utilities/parsing.py:263: UserWarning: Attribute 'model' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model'])`.
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Error executing job with overrides: ['log.run=1', 'log.proj_name=SEED_test', 'data=SEED', 'model.timeFilterLen=30', 'model.dilation_array=[1,3,6,12]', 'model.seg_att=15', 'model.avgPoolLen=15', 'model.timeSmootherLen=3', 'train.gpus=[0]', 'train.valid_method=loo', 'train.num_workers=0', 'train.iftest=True']
Traceback (most recent call last):
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/train_ext.py", line 86, in train_ext
    trainer.fit(Extractor, dm)
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1042, in _run
    self._data_connector.prepare_data()
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 109, in prepare_data
    self.trainer._call_lightning_datamodule_hook("prepare_data")
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/data/pl_datamodule.py", line 26, in prepare_data
    EEG_Dataset(self.cfg,sliced=False)
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/data/dataset.py", line 137, in __init__
    data, onesub_labels, n_samples_onesub, n_samples_sessions = load_EEG_data(self.load_dir,cfg)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/data/io_utils.py", line 18, in load_EEG_data
    data, onesub_labels, n_samples_onesub, n_samples_sessions = load_data_func(
                                                                ^^^^^^^^^^^^^^^
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/data/io_utils.py", line 226, in load_processed_SEED_NEW_data
    list_files = os.listdir(dir)
                 ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\\\\10.16.32.74\\dataset0\\qingzhu\\AutoICA_Processed_EEG\\SEED\\Processed_data_filter_0.50_47.00_AutoICA_Def_Threshold\\data_3in1/processed_data'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.