/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/pytorch_lightning/loggers/wandb.py:395: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
Error executing job with overrides: ['log.run=2', 'log.proj_name=SEED_test_loo', 'data=SEED', 'model.timeFilterLen=30', 'model.dilation_array=[1,3,6,12]', 'model.seg_att=15', 'model.avgPoolLen=15', 'model.timeSmootherLen=3', 'train.gpus=[0]', 'train.valid_method=loo', 'train.num_workers=8', 'train.iftest=False']
Traceback (most recent call last):
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/train_mlp.py", line 89, in <module>
    train_mlp()
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ncclab/shenxinke/att_model/CLISA_Hydra/train_mlp.py", line 57, in train_mlp
    data2 = np.load(save_path)
            ^^^^^^^^^^^^^^^^^^
  File "/home/ncclab/miniconda3/envs/att_model/lib/python3.11/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dataset0/qingzhu/AutoICA_Processed_EEG/SEED/Processed_data_filter_0.50_47.00_AutoICA_Def_Threshold/data_3in1/ext_fea/fea_r2/_r2_f10_fea_me.npy'
[1m---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1mtrain_mlp.py 89 <module>
[1mtrain_mlp()
[1mmain.py 94 decorated_main
[1m_run_hydra(
[1mutils.py 394 _run_hydra
[1m_run_app(
[1mutils.py 457 _run_app
[1mrun_and_report(
[1mutils.py 223 run_and_report
[1mraise ex
[1mutils.py 220 run_and_report
[1mreturn func()
[1mutils.py 458 <lambda>
[1mlambda: hydra.run(
[1mhydra.py 132 run
[1m_ = ret.return_value
[1mutils.py 260 return_value
[1mraise self._return_value
[1mutils.py 186 run_job
[1mret.return_value = task_function(task_cfg)
[1mtrain_mlp.py 57 train_mlp
[1mdata2 = np.load(save_path)
[1mnpyio.py 427 load
[1mfid = stack.enter_context(open(os_fspath(file), "rb"))
[1mFileNotFoundError:
[1m2
[1mNo such file or directory
[1m/mnt/dataset0/qingzhu/AutoICA_Processed_EEG/SEED/Processed_data_filter_0.50_47.00_AutoICA_Def_Threshold/data_3in1/ext_fea/fea_r2/_r2_f10_fea_me.npy
[2024-05-18 16:01:02,874][__main__][INFO] - fold:10
[2024-05-18 16:01:02,875][__main__][INFO] - train_subs:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14]
